import { createSlice } from "@reduxjs/toolkit";

/**
 * Initial state for cart slice
 * -----------------------------
 * items: Array to store all products added to the cart.
 * Each item contains product details along with quantity.
 */
const initialState = {
  items: [],
};

/**
 * cartSlice
 * ----------
 * This slice manages all cart-related state and logic.
 * Redux Toolkit's createSlice automatically generates
 * action creators and reducer functions.
 *
 * Assignment Mapping:
 * - Redux state management
 * - Actions and reducers for cart operations
 */
const cartSlice = createSlice({
  name: "cart",
  initialState,
  reducers: {
    /**
     * addToCart
     * ----------
     * Adds a product to the cart.
     * - If the product already exists, increase its quantity.
     * - Otherwise, add it with quantity = 1.
     */
    addToCart: (state, action) => {
      const existing = state.items.find(
        (item) => item.id === action.payload.id
      );

      if (existing) {
        existing.quantity += 1;
      } else {
        state.items.push({
          ...action.payload,
          quantity: 1,
        });
      }
    },

    /**
     * removeFromCart
     * ----------------
     * Removes a product completely from the cart
     * using its unique product ID.
     */
    removeFromCart: (state, action) => {
      state.items = state.items.filter((item) => item.id !== action.payload);
    },

    /**
     * updateQuantity
     * ----------------
     * Updates the quantity of a cart item.
     * Quantity is restricted to a minimum value of 1.
     */
    updateQuantity: (state, action) => {
      const item = state.items.find((item) => item.id === action.payload.id);

      if (item && action.payload.quantity >= 1) {
        item.quantity = action.payload.quantity;
      }
    },

    /**
     * clearCart
     * ----------
     * Empties the entire cart.
     * Used after successful checkout.
     */
    clearCart: (state) => {
      state.items = [];
    },
  },
});

/**
 * Export actions generated by createSlice
 */
export const { addToCart, removeFromCart, updateQuantity, clearCart } =
  cartSlice.actions;

/**
 * Export reducer to be added to Redux store
 */
export default cartSlice.reducer;
